### ISSUE TITLE
Не происходит пополнение баланса до уровня максимального баланса (#test13)

### ISSUE THREAD

**Issue by supernatashenka** [DianaBasenkova/java_QA56_diploma#10]
# Описание
Не происходит пополнение баланса на сумму пополнения в пределах максимального лимита. В результате отображен начальный баланс вместо суммы начального баланса + суммы пополнения. 

# Локация дефекта 
  https://github.com/DianaBasenkova/java_QA56_diploma/blob/0a2c9cce5509aa1855c7786f94652a34386cdd8c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1. Открыть код в Intellij IDEA
2. Создать в тестовом классе новый объект сберегательного счета, назначить начальный баланс  2_000, минимальный баланс 1000, максимальный баланс 10_000, процентную ставку 5.
3. Применить метод "add", назначить сумму пополнения 8_000. 

*Ожидаемый результат:* Итоговый баланс = 10_000
*Фактический результат:* Итоговый баланс = 2_000

# Тест 
https://github.com/DianaBasenkova/java_QA56_diploma/blob/0a2c9cce5509aa1855c7786f94652a34386cdd8c/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L181

# Скриншот 
![image](https://user-images.githubusercontent.com/122474543/231229136-f0ab7c73-1633-4475-b237-7cacb3becf09.png)

# Окружение 
ОС - Windows 11
Java - JDK coretto-11(Amazon coretto version 11.0.18)
IDE - Intellij IDEA Community Edition 2022.3.2

**Comment by DianaBasenkova** [comment]
Внесены исправления в метод Add для saving account

**Comment by DianaBasenkova** [comment]
Исправлено.
Добавлено условие что балланс может быть не только меньше максимального лимита, но и равен ему.
https://github.com/DianaBasenkova/java_QA56_diploma/blob/b3b177d2bcfe380c477f3ea76c06393420dc963a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L86
Исправлена логика расчета нового баланса
https://github.com/DianaBasenkova/java_QA56_diploma/blob/b3b177d2bcfe380c477f3ea76c06393420dc963a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87
