### ISSUE TITLE
Не реализовано исключение, где текущий баланс меньше минимального (#test2)

### ISSUE THREAD

**Issue by supernatashenka** [DianaBasenkova/java_QA56_diploma#19]
# Описание
Не реализовано исключение, где текущий баланс меньше минимального 

# Локация дефекта 
https://github.com/DianaBasenkova/java_QA56_diploma/blob/0a2c9cce5509aa1855c7786f94652a34386cdd8c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L24

# Шаги воспроизведения
1. Открыть код в Intellij IDEA
2. Создать в тестовом классе новый объект сберегательного счета, назначить начальный баланс  500, минимальный баланс 1_000, максимальный баланс 9_000, процентную ставку 1.

*Ожидаемый результат:* Тест пройден с учетом исключения. 
*Фактический результат:* Отображена ошибка: "Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown."

# Тест 
https://github.com/DianaBasenkova/java_QA56_diploma/blob/0a2c9cce5509aa1855c7786f94652a34386cdd8c/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L20

# Скриншот 
![image](https://user-images.githubusercontent.com/122474543/231236144-1a2f4a47-575b-4e9c-a50e-2181c8318e81.png)

# Окружение 
ОС - Windows 11
Java - JDK coretto-11(Amazon coretto version 11.0.18)
IDE - Intellij IDEA Community Edition 2022.3.2

**Comment by DianaBasenkova** [comment]
Исправлено.
Созданы: исключение и класс, обрабатывающий исключения.
https://github.com/DianaBasenkova/java_QA56_diploma/blob/b3b177d2bcfe380c477f3ea76c06393420dc963a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L36
https://github.com/DianaBasenkova/java_QA56_diploma/blob/b3b177d2bcfe380c477f3ea76c06393420dc963a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L37
