### ISSUE TITLE
Не реализовано исключение для создания аккаунта, где минимальный баланс больше максимального в SavingAccount (#Test4)

### ISSUE THREAD

**Issue by supernatashenka** [DianaBasenkova/java_QA56_diploma#22]
# Описание
Не реализовано исключение для создания аккаунта, где минимальный баланс больше максимального 

# Локация дефекта 
https://github.com/DianaBasenkova/java_QA56_diploma/blob/0a2c9cce5509aa1855c7786f94652a34386cdd8c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L24

# Шаги воспроизведения
1. Открыть код в Intellij IDEA
2. Создать в тестовом классе новый объект сберегательного счета, назначить начальный баланс  3_000, минимальный баланс 10_000, максимальный баланс 1_000, процентную ставку 1.

*Ожидаемый результат:* Тест пройден с учетом исключения. 
*Фактический результат:* Отображена ошибка: "Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown."

# Тест 
https://github.com/DianaBasenkova/java_QA56_diploma/blob/0a2c9cce5509aa1855c7786f94652a34386cdd8c/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L38

# Скриншот 
![image](https://user-images.githubusercontent.com/122474543/231241232-1ccde933-6c2a-4d78-8f93-6ac8130935a0.png)

# Окружение 
ОС - Windows 11
Java - JDK coretto-11(Amazon coretto version 11.0.18)
IDE - Intellij IDEA Community Edition 2022.3.2

**Comment by DianaBasenkova** [comment]
Реализовано в рамках исключения по initialBalance
https://github.com/DianaBasenkova/java_QA56_diploma/blob/b3b177d2bcfe380c477f3ea76c06393420dc963a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L32
